src/main/groovy/jaci/openrio/gradle/GradleRIO.groovy
This updates the MDNS name for the new scheme being used in 2016. The name was changed to roborio-number-frc.local to prevent MDNS number incrementing issues. Basically, when MDNS detects conflicts, it will append a number to the end and increment it. So in previous years, roborio-190.local would become roborio-191.local, then roborio-192.local, and so on. Now, it will start as roborio-190-frc.local, then go to roborio-190-frc-1.local, and so on.
=> Updated the MDNS name for 2016

quickstart/build.gradle
The default value of robotClass did not have the robot package before
the Robot class.
=> Fixed robotClass scheme

src/main/groovy/jaci/openrio/gradle/wpi/toolchain/WPIRoboRioGcc.groovy
--sysroot is not a valid argument for GCC's linker, assembler, or static archiver.
This should fix issue #52, though this is untested
=> Removed invalid arguments

src/main/groovy/jaci/openrio/gradle/ExternalLaunchTask.groovy, src/main/groovy/jaci/openrio/gradle/sim/JavaSimulationTask.groovy, src/main/groovy/jaci/openrio/gradle/sim/NativeSimulationTask.groovy, src/main/groovy/jaci/openrio/gradle/wpi/dependencies/WPICommonDeps.groovy
With these 3 patches, and a modestly hacked _localtest, I am able to generate scripts on Linux that work with the simulateMyFrcBinary and simulateJar tasks.
This works only if I remove the AHRS and CTRE code from the samples in _localtest; we still need to resolve those libraries.
=> A set of changes to enable the simulation targets

src/main/groovy/jaci/openrio/gradle/ide/EditorConfigurationTask.groovy
Needed in order to set up include paths for vscode. The source directory shouldn't be included in the header list, otherwise we have a disconnect between gradle and intellisense.
=> Add ExportedHeaders to it's own json list in editor

src/main/groovy/edu/wpi/first/gradlerio/frc/FRCPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/frc/TeamNumberNotFoundException.groovy
Closes #124
Parses the file after the command line arguments. Also adds a getTeamValue call that takes no parameter, and throws if if can't find a team number
That way we don't need a team number at all in the gradle file
=> Add parsing the wpilib json file for team number

src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIToolchainExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIToolchainPlugin.groovy
Currently will always happen, should add a way to disable at some point. But in theory, it is a change that is always safe to do.
=> Add output stripping to binaries built with rio compiler

build.gradle, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
This way we don't need to modify multiple imports during updates. It only gets applied if there is a native project
=> Add GradleRIO dependency for Gradle VS Code extension

build.gradle, src/test/groovy/edu/wpi/first/gradlerio/GradleRioInitializationTest.groovy
With just the Java or C++ plugin and nothing else, configuration should be successfull
Regrestion tested, and this would have caught #161
=> Add base tests to make sure Java and C++ projects init correctly

build.gradle, src/main/groovy/edu/wpi/first/gradlerio/frc/FRCPlugin.groovy
Depends on EmbeddedTools https://github.com/JacisNonsense/EmbeddedTools/pull/24
Replaces artifact('frcJava', edu.wpi.first.gradlerio.frc.FRCJavaArtifact)
with
frcJavaArtifact('frcJava')
=> Add simplified target and artifact extensions

src/main/resources/ScriptBase.vbs
Now waits 3 seconds, and reports if the tool failed to launch, which happens with bad java versions
=> Update VBS Script used to launch tools

src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPICommonDeps.groovy
These are useful when trying to do local development. Theyre verbose because we don't normally want them enabled.
=> Add way to enable the wpilib development in releases that get put in ~/releases/maven

src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJavaDeps.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDeps.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIRoboRioGcc.groovy, versionupdates.gradle
For now, don't run the update versions task, + is currently broken because of an upstream change
=> Bump to working 2019 versions of all dependencies

src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.groovy, src/test/groovy/edu/wpi/first/gradlerio/wpi/WPIExtensionExtendableTest.groovy, src/test/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtensionExtendableTest.groovy
Cleaner then casting ExtensionAware, and safer too, as it doesn't create a named extension
Also adds tests to ensure the things are always extendable
=> Use ObjectFactory to create extendable objects for DSL

build.gradle, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDeps.groovy
They were including both shared and static libraries, which was very breaking
In addition, opencv on windows needed to exclude a specific library.
I also added _static library specs for everything. So if an all static build is wanted, it is possible to get it
=> Fixes desktop builds

build.gradle, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJavaDeps.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDeps.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIToolchainPlugin.groovy
This immensely cleans up simulation, specifically on windows, where it was basically needed
Requires an ET change
I also still need to update the build settings that get used.
=> Adds changes needed for separate debug and release dependencies

src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
It seems that the cast from GString to String is failing here. The `toString()` cast is present when returning other dependencies but it isn't present on this one.
Log:
```
class org.codehaus.groovy.runtime.GStringImpl cannot be cast to class java.lang.String (org.codehaus.groovy.runtime.GStringImpl is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @7823a2f9; java.lang.String is in module java.base of loader 'bootstrap')
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
```
=> Fix GString to String type cast failing

src/main/groovy/edu/wpi/first/gradlerio/GradleRIOPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/JsonMergeTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/JsonUtil.groovy, src/main/groovy/edu/wpi/first/gradlerio/frc/DebugInfoMergeTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/frc/DebugInfoTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/frc/FRCPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/ExternalSimulationMergeTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/ExternalSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/JavaExternalSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/JavaTestPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/NativeExternalSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/NativeTestPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/TestPlugin.groovy
Makes sim work better in multiproject builds / builds with multiple simulation targets. Likewise for RoboRIO debug configurations.
Correctly labels sim / debug candidates with their project name for identification, and makes all projects place it into the rootProject such that vscode can find it. 
Also adds a small fix to singleton tasks, wherein the last task is the only one executed, not the first (required for tasks that 'merge' files together)
=> External sim fix, Fixes #291

src/main/groovy/edu/wpi/first/gradlerio/frc/FRCJREArtifact.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.groovy
Also fixes a newly-discovered bug where if the jar task was up to date (no changes in .java files), missing JNI deps wouldn't redownload
=> Download jre .ipk preemptively, fixes #294

src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
Forward allows v14 image which should not have header changes.
=> Forward allow v14 image

src/main/groovy/edu/wpi/first/gradlerio/frc/FRCJavaArtifact.groovy
Change java.lang.invoke.stringConcat to BC_SB.  See https://www.chiefdelphi.com/t/improbable-java-slow-down-in-combining-doubles-and-strings/350331/20
Change to CMS garbage collector.  See https://www.chiefdelphi.com/t/timedrobot-loop-overruns-and-inconsistent-loop-timing-java/348953/25
=> Fix two Rio JRE slowdown issues (string concat and GC)

src/main/groovy/edu/wpi/first/gradlerio/frc/FRCPlugin.groovy
Solves most of the deprecation issues that pop up during the build. Not a general case fix, as that requires a large number of changes.
I still need to test this when I get home, as it requires a rio.
=> Resolve Maven Configuration Artifacts before deploying

build.gradle, examples/java/build.gradle, examples/kotlin/build.gradle, src/main/groovy/edu/wpi/first/gradlerio/GradleRIOPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDepsExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
Make it more explicit so it matches the vendor code. Also will make it easier to add more platforms, as well as combined jars.
Also makes switching between debug and release in java possible.
=> Clean up how JNI is added to the project

src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeJsonDepRules.groovy
You won't be able to deploy to a stock 2020 image, as its missing a dependent library.
=> Update to 2020 image being used

build.gradle
Hi
This commit adds missing dependencies between zip-related tasks and patch examples.
As it is shown above, `PatchExamples` can be executed after zip-related tasks,
leaving archives in an inconsistent state.
```
> Task :zipExamplejava
Caching disabled for task ':zipExamplejava' because:
Build cache is disabled
Task ':zipExamplejava' is not up-to-date because:
Input property 'rootSpec$1$1' file /root/GradleRIO/examples/java/build.gradle has changed.
:zipExamplejava (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.019 secs.
:PatchExamples (Thread[Execution worker for ':' Thread 2,5,main]) started.
> Task :PatchExamples
Caching disabled for task ':PatchExamples' because:
Build cache is disabled
Task ':PatchExamples' is not up-to-date because:
Task has not declared any …
```
=> Add missing dependencies between zip and patch examples

src/main/groovy/edu/wpi/first/gradlerio/frc/FRCJavaArtifact.groovy
This reverts commit 218e8c791eb40b1229651dbbe2250b20cea4ebf5.
This caused a long slowdown for first string concatenation using the code here:
https://www.chiefdelphi.com/t/improbable-java-slow-down-in-combining-doubles-and-strings/350331
It is ~40ms with BC_SB and ~560ms with methodhandle "MH_INLINE_SIZED_EXACT"
=> Revert "use methodhandle-based generator for string concatenation

README.md, build.gradle, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/VendorDepTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.groovy
Fixes #417 
The original commit uses curl, the second uses the [gradle-download plugin](https://github.com/michel-kraemer/gradle-download-task).
=> Add a vendordep gradle task

src/main/groovy/edu/wpi/first/gradlerio/ExternalLaunchTask.groovy
Fixes #419 
Turns out that the problem was with the format the `start` command parses its parameters ([source](https://ss64.com/nt/start.html)):
```cmd
START "title" [/D path] [options] "command" [parameters]
```
In the current/old code, the absolute filepath to the script is parsed as the command, but windows filepath resolving gets messed up with spaces. If we quote the filepath to go around the spacing issue, `start` parses it as the title and nothing is executed. 
In the new code, we give `start` a title so the filepath is correctly identified as the command, and quote the filepath so windows resolves the path correctly.
I checked Java simulations (both with spaces and without), everything succeeded.
Can someone please check on MacOS/Linux to see if UNIX path resolving works with …
=> Fix simulateJava behaviour when filepath has spaces

src/main/groovy/edu/wpi/first/gradlerio/ExternalLaunchTask.groovy
Resolves #465 
- Java works well:
```groovy
simulateJava {
envVar "myvariable", "value"
}
```
- C++ works as well, but a bit verbose/annoying:
```groovy
tasks.withType(edu.wpi.first.gradlerio.test.NativeSimulationTask.class) {
envVar "myvariable", "value"
}
```
I will experiment a bit more to make C++ cleaner.
Thoughts?
=> Add support for custom env vars in sim

gradle.properties, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
Several tools still have version detection issues and are thus beta-2.
=> Update for 2021.1.1-beta-3

src/main/groovy/edu/wpi/first/gradlerio/ExternalLaunchTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/JavaExternalSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/JavaSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/NativeExternalSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/test/NativeSimulationTask.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/simulation/HalSimExtension.groovy, src/main/groovy/edu/wpi/first/gradlerio/wpi/simulation/SimulationExtension.groovy
Replaces #466 
The way this works is completely different. Instead of setting on the individual tasks, theres a new global extension `sim` that is used. So the following block would be used, and replaces what was there.
```
sim {
envVar "myVar", "value"
}
```
Since its a map, you can also do 
```
sim {
environment "myVar", "value"
}
```
But I wanted to leave the old method there so its trivial to replace.
Theres also a hidden goodie that might make it for 2021 that will improve extensions as well :D
=> Support setting sim env vars for VS Code

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/InvalidImageException.java, src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
This will help for determining why the parsing failed
```
admin @ roborio-330-FRC.local: Connected.
Reason: InvalidImageException
Could not parse image version!
/etc/natinst/share/scs_imagemetadata.ini contents:
[ImageMetadata]
IMAGEDESCRIPTION = ""
IMAGEID = "{69BE94A1-A4B5-47BC-A41F-C60F0E5030A6}"
IMAGETITLE = "roboRIO Image"
IMAGEVERSION = "FRC_roboRIO99_2022_v3.2"
```
=> Print image file contents when unable to parse image version

src/main/java/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.java, src/main/java/edu/wpi/first/gradlerio/wpi/WPIMavenRepo.java, src/main/java/edu/wpi/first/gradlerio/wpi/WPIPlugin.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.java
This PR is a few changes. The first is updates to the frc maven vendor cache. This allows vendors to state if theyre included or not in the cache. This will speed up builds for vendors not in the cache.
Secondly, this adds repository filtering. This means that for vendors only group ids listed by the vendors will be searched. Closes #500 
Both of these changes are backwards compatible. Old vendor deps will still work, and they default to not being included in the cache.
=> Updates to vendor configuration

src/main/java/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.java, src/main/java/edu/wpi/first/gradlerio/wpi/WPIMavenRepo.java, src/main/java/edu/wpi/first/gradlerio/wpi/WPIPlugin.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.java
The incorrect URL was causing the UI URL to be used, causing the cache to be much slower, especially if there were artifacts not in the cache. This had us add a new field to the vendor json spec. But with the right URL, this is not longer necessary.
=> Use correct vendor cache url

src/main/resources/ScriptBase.py
Fixes macOS pop-up and Ubuntu 20.04
=> Explicitly require python3

README.md
It no longer exists in GradleRIO, and it doesn't really make sense to be in gradlerio either.
=> Remove references to riolog

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
This reverts commit 83427d81a220571cff762932e13d85a0b93be06b.
This is still needed, at least in the 1.2 image.
=> Revert "Remove sed changes during deploy (#613)"

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
This reverts commit 804646c2167402634b53bb14021ed2923efe9792.
The v1.3 image seems to have this on both images. I'll run some extra deployment tests to double check.
=> Revert "Revert "Remove sed changes during deploy (#613)" (#615)"

build.gradle
Theres major changes to both the deploy and toolchain plugins. The toolchain plugin is a bit lazier now, which should make windows configuration faster. The deploy plugin now no longer uses static fields to share state to workers, which should be cleaner, and less chance of breaking.
=> Update native utils to 2023.4.1

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCJavaArtifact.java
This was a good idea in theory, but with the limited ram resources on the roboRIO this can result in issues
=> Remove AlwaysPreTouch from java arguments

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
The 2024 image doesn't have an "FRC_" prefix.
Fixes https://github.com/wpilibsuite/2024Beta/issues/6.
=> Loosen image version check

src/main/java/edu/wpi/first/gradlerio/GradleRIOPlugin.java, src/main/java/edu/wpi/first/gradlerio/OneDriveException.java
=> Fix #677 Error if project is in OneDrive

.gitattributes
The overwrite for frcKillRobot.sh was getting corrupted by default on windows
=> Force .sh scripts to always be pulled as lf

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
https://github.com/wpilibsuite/allwpilib/issues/6257 was causing the CPU to spin. Due to this, ssh took about 4 seconds to connect, which is higher than the timeout of 3 seconds, so it wouldn't connect. Increase the timeout to attempt to make this case still work.
=> Increase ssh timeout from 3 to 7 seconds

src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPINativeCompileRules.java
Because of the Iterator, the IOException is actually an UncheckedIOException rather than an IOException. So the added try catch wasn't catching the exception. Instead just catch all exceptions intead.
=> Catch all exceptions in printWarningsForBinTask

README.md, src/main/java/edu/wpi/first/gradlerio/deploy/roborio/GarbageCollectorType.java
Since allwpilib now targets JDK 17, 11 won't work any more. https://github.com/wpilibsuite/allwpilib/pull/6585
=> Remove CMS JDK type and JDK 11 instructions

.github/workflows/ci.yml
Files/directories starting with `.` are now considered "hidden" and won't be uploaded by default. Uploading only the repository makes it so .m2 isn't in the recursive glob, and ensures settings.xml doesn't get uploaded (good practice since it can potentially contain repository credentials)
=> Fix build artifact upload

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCJNILibraryArtifact.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/CppToolRunTask.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/ToolInstallTask.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/ToolRunTask.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPICppTool.java
Includes much nicer warning APIs. Includes a lot of deperecations, so we need to test things
=> Update to gradle 8.11

.github/workflows/ci.yml, src/main/java/edu/wpi/first/gradlerio/deploy/systemcore/FRCNativeArtifact.java, src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
ldconfig doesn't currently work, so we need to directly pass LD_LIBRARY_PATH for C++. 
Also updates the included library version. This includes working CAN and PWM support.
=> Fix systemcore c++ deploy

src/main/java/edu/wpi/first/gradlerio/deploy/roborio/InvalidImageException.java
Previously, the URL merged with the text:
=> Add missing whitespace in InvalidImageException

src/main/java/edu/wpi/first/gradlerio/wpi/simulation/SimulationExtension.java
Desktop platforms don't split out debug info, but arm platforms do. The logic we used didn't account for this.
Closes https://github.com/wpilibsuite/allwpilib/issues/7631
=> Fix arm64 linux simulation

README.md, src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java, src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPIToolsPlugin.java, versionupdates.gradle
These tools are no longer shipped as part of 2027, and break the installer if they're in here.
=> Remove old java tools

src/main/java/edu/wpi/first/gradlerio/wpi/WPIExtension.java, testing/asm/settings.gradle, testing/java/settings.gradle, testing/jni/settings.gradle
In past betas we used just the year which let beta vendordeps be use with releases. This will make beta vendordeps only loadable with on beta projects
=> Update frcYear to 2026beta
