wpilibsuite/GradleRIO

- release/build.gradle
It was giving me an error after changing the team names, and changing this allowed it to work.
Before: http://puu.sh/jPPur/64db60efeb.png
After: http://puu.sh/jPPvC/e59174b12a.png
> Change version to latest release

- src/main/groovy/jaci/openrio/gradle/WPIProvider.groovy
Fixes #8. Easy enough fix that I can quickly make a pull request for you.
> Fixed maven url to use the release repository

- examples/coprocessor_java/README.md
- examples/coprocessor_java/build.gradle
- examples/coprocessor_java/common/build.gradle
- examples/coprocessor_java/common/src/main/java/gradlerio/Constants.java
- examples/coprocessor_java/coprocessor/build.gradle
- examples/coprocessor_java/robot/build.gradle
- examples/coprocessor_java/robot/src/main/java/gradlerio/RobotExample.java
- examples/coprocessor_java/settings.gradle
Hopefully this Gradle config addition is useful!  I was setting up this coming season's project structure and wanted to help contribute back.  Thanks for your hard work!
> Added an example of inter-project dependency to coprossessor_java

- docs/01-installing-gradlerio.md
- src/main/groovy/jaci/openrio/gradle/wpi/toolchain/install/LinuxToolchainInstaller.groovy
One to make the linux install flow smoother, and another to update the documentation slightly.
> A few small tweaks to GradleRIO 

- build.gradle
- src/main/resources/META-INF/gradle-plugins/jaci.openrio.gradle.GradleRIO.properties
Required for local publish to properly work
> Uses built in manifest generation

- src/main/groovy/jaci/openrio/gradle/frc/FRCNativeLibraryArtifact.groovy
Allows just deploying native libraries to the lib folder
> Adds FRCNativeLibraryArtifact

- _localtest/build.gradle
- src/main/groovy/jaci/openrio/gradle/wpi/WPIPlugin.groovy
- src/main/groovy/jaci/openrio/gradle/wpi/dependencies/WPICommonDeps.groovy
- src/main/groovy/jaci/openrio/gradle/wpi/dependencies/WPIJavaDeps.groovy
- src/main/groovy/jaci/openrio/gradle/wpi/dependencies/WPINativeDeps.groovy
Also renames the classifier for that desktop, as that is likely what will make more sense to docs and users.
> Uses JVM bitness for simulation on windows

- src/main/groovy/jaci/openrio/gradle/wpi/dependencies/WPINativeDeps.groovy
Note this will interfere with #106, so we should merge that one first.
> Adds wpilibjni configuration

- build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPIToolsPlugin.groovy
- versionupdates.gradle
Versions that are leaving for beta were skipped, which is why there are so few dependencies
Depends on #149
> Add task to automatically update WPILib dependencies to newest version

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPICommonDeps.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJavaDeps.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDeps.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIToolchainPlugin.groovy
Uses development for now until we have a beta release published to release maven.
> Adds 2019 libraries

- build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJsonDepsPlugin.groovy
Very WIP, but want to do it in the open for feedback.
> Starts work on adding JSON dependnecies

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPICommonDeps.groovy
These should be done through vendor libraries
> Remove unused repositories

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJsonDepsPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeJsonDepRules.groovy
Model was getting applied in all cases, which is incorrect.
> Fix Java only builds

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPICommonDeps.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJavaDeps.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJsonDepsPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDeps.groovy
This was used in multiple places, and could be useful from user side scripts as well
> Moves nativeclassifier functionality to wpiExtension

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIJsonDepsPlugin.groovy
Allows use in google test, and the ET dds fix
Closes #173
> Fix vendor deps in C++ projects

- src/main/groovy/edu/wpi/first/gradlerio/GradleRIOPlugin.groovy
This needs to be a user settable property.
> Use passed in main class for java manifest

- build.gradle
- src/test/groovy/edu/wpi/first/gradlerio/GradleRioInitializationTest.groovy
Adds test to ensure this doesn't happen again
> Update VS Code Cpp extension to fix subproject bug

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeJsonDepRules.groovy
For the linux installer, I can't build it directly on linux. So I need to build it on windows, but need the other OS classifiers
> Add way to force a native classifier for a project

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/tools/ToolRunException.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/tools/ToolRunTask.groovy
- src/main/resources/ScriptBase.vbs
Properly pipe any startup errors to GradleRIO and the message box (not used in GR but elsewhere)
Also fixes #192
> Add smarter tool running on windows

- .vscode/settings.json
- examples/_archived/coprocessor_cpp/robot/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/frc/RoboRIO.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/ToolchainDiscoverer.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIRoboRioGcc.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIToolchainPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/install/LinuxToolchainInstaller.groovy
These should be the last changes needed from my side, other then the wpilib versions. We can leave this PR open until jenkins is publishing everything and we can add those.
> Compiler and frc year updates for 2019

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/WPIToolchainPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/install/LinuxToolchainInstaller.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/install/MacOSToolchainInstaller.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/toolchain/install/WindowsToolchainInstaller.groovy
Will be faster in other areas of the country, and scale better then our server
I thought this was commited in the other PR, but the git push failed...
> Move to github for retreiving toolchains

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
> Update to -3 patch for compiler

- build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/frc/riolog/RiologPlugin.groovy
- src/test/groovy/edu/wpi/first/gradlerio/GradleRioInitializationTest.groovy
Configuration would error before this
> Fix riolog configuration happening out of order

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDepsExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeJsonDepRules.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
> Add support for wpilib version sentinal in vendor deps

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPINativeCompileRules.groovy
> Add CPP Compile Warnings

- build.gradle
Fixes deprecation error in user projects.
> Update the vscode extension

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeJsonDepRules.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
Force debug on rio, release on raspbian, do what the debugSimJNI property says otherwise
> Support debug libraries in JNI

- ToolchainPlugin/build.gradle
- build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/frc/FRCNativeArtifact.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDepRules.groovy
opencv is becoming a requirement in beta 4, and ni libraries were a good idea. All debug things should be linked to debug
> Use debug libraries for opencv and ni libraries

- src/main/groovy/edu/wpi/first/gradlerio/frc/DebugInfoTask.groovy
> Add support for debugging external artifacts

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPINativeCompileRules.groovy
> Only apply compiler args to platforms GradleRIO knows about

- ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainPlugin.java
- ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPINativeCompileRules.groovy
Useful for all toolchains make by the toolchain plugins, not just the rio one
Closes #256
> Move Strip Task to toolchain plugin

- ToolchainPlugin/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPINativeCompileRules.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeJsonDepRules.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
> Vendordeps loadfrom

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.groovy
- versionupdates.gradle
Used for the nightly builder. Also sets the flag in WPIMavenExtension to match which mode was used.
> Add way to specify development vs release for UpdateVersion task

- README.md
- build.gradle
- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
Also adds a task to zip examples for release
> Update README for 2019

- src/main/groovy/edu/wpi/first/gradlerio/DownloadAllTask.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.groovy
> Resolve RoboRIO JNI Deps during build

- build.gradle
- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/frc/DebugInfoTask.groovy
Ugh gradle having multiple syntaxes is annoying...
> Fix extra artifacts in debug task

- src/main/groovy/edu/wpi/first/gradlerio/test/JavaSimulationTask.groovy
Fixes #283, as multiple executable jars breaks other things in parts of gradle as well.
> Only use executable jars for JavaSimulationTask

- src/main/groovy/edu/wpi/first/gradlerio/ide/GenerateClionTask.groovy
> Fix clion debug vs release files

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPINativeDepRules.groovy
> Fix JNI sim library name to properly work

- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
PathWeaver was intentionally left at 2019.2.1.
> Update to 2019.3.1

- ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/GccToolChain.java
- ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
Otherwise you have to skip even an unknown toolchain
> Ignore not found toolchains if theyre never used

- src/main/groovy/edu/wpi/first/gradlerio/frc/FRCNativeArtifact.groovy
Sometimes, file is locked causing the scp to fail
> Remove file to deploy before deploying

- build.gradle
- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
> Update to 2019.4.1

- build.gradle
> Update Gradle VSCode CPP plugin

- examples/java/build.gradle
- examples/kotlin/build.gradle
Equivalent to https://github.com/wpilibsuite/vscode-wpilib/pull/256
> Use compileClasspath in example build.gradle files

- src/main/groovy/edu/wpi/first/gradlerio/frc/FRCPlugin.groovy
Reverts wpilibsuite/GradleRIO#310
> Revert "Resolve Maven Configuration Artifacts before deploying"

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
It's going to become optional in Native Utils, so force it back to non optional here
> Set rio compiler to not optional

- build.gradle
- examples/cpp/src/main/cpp/robot.cpp
- examples/java/src/main/java/frc/team0000/robot/Robot.java
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDepsExtension.groovy
- versionupdates.gradle
Currently set to use the development repo by default. Will need to be switched back
> Full updates to be compatible with 2020 artifacts

- build.gradle
- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
No change to users, just a change in the lower level dependency
> Bump native utils version to now require the roborio to be added

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDepsExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPISimDepsExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
> Update how sim code is added

- build.gradle
- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/JsonMergeTask.groovy
- src/main/groovy/edu/wpi/first/gradlerio/test/ExternalSimulationTask.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPISimDepsExtension.groovy
Also fixes a few bugs causing configurations not to update. At some point things should be made incremental, but this works for now
> Get Sim GUI working

- build.gradle
- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/kotlin/build.gradle
> Update native-utils to not deploy debug files

- src/main/groovy/edu/wpi/first/gradlerio/test/NativeTestPlugin.groovy
> Include RUNNING_FRC_TESTS in C builds

- build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
Fixes vscode file not regenerating, and vscode including the wrong files
> Update to beta 4

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPISimDepsExtension.groovy
> Fix halsim dependencies being incorrect

- src/main/groovy/edu/wpi/first/gradlerio/test/JavaSimulationTask.groovy
> Make Java Simulation task use wpilib JDK, message about potential missing runtime

- README.md
Update README.md's explanation about using IntelliJ and Eclipse as IDEs with GradleRIO
> Update README.md IDE support

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.groovy
Resolves #432
@ThadHouse - the warning message probably needs some rewording/reworking, any ideas? And I couldn't find other locations of the "default-or-warning" part, feel free to point me in the direction of one to imitate.
> Add `wpi.deps.vendor.folderpath` as mutable property

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPISimDepsExtension.groovy
Also remove print, nt_ds, and lowfi as these are no longer built.
> Update sim extensions (add ws_server and ws_client)

- README.md
Fixes #431 
@sciencewhiz can you make sure that the articles I linked are the articles that should be linked?
> Update frc-docs links in README

- build.gradle
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/WPIDepsExtension.groovy
- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPIToolsPlugin.groovy
- versionupdates.gradle
> Update to latest dependency layout for all tools, add wpilib math, use dev repo

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIPlugin.groovy
> Rename task `wpi` -> `wpiVersions`

- build.gradle
- gradle.properties
Fixes #428 
Are there any more properties that can/should be moved; or any properties that I have moved and shouldn't be?
> Move some properties to separate file

- README.md
Remove outdated reference to Pathfinder
> Update Readme description of Pathweaver

- examples/java/.vscode/settings.json
- examples/jni/.vscode/settings.json
We don't want the hybrid engine for users
> Default Java projects to auto import into full intellisense engine.

- build.gradle
This fixes a security vulnerability: https://blog.gradle.org/plugin-portal-update
> Update gradle-publish plugin to 0.12.0

- src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/VendorDepTask.groovy
> Change vendordep task local key

- src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
Resolve #460 
@sciencewhiz Is more than this needed? If yes, what?
> Update RoboRIO JRE

- src/main/groovy/edu/wpi/first/gradlerio/frc/InvalidImageException.groovy
Fixes #302 
@Daltz333 do you think a different frc-docs article should be linked, or the link should not be to `/latest/`?
I don't like that the URL isn't in on one line in the source code, but without wrapping it passes the 100 char line limit.
Thoughts?
> Expand InvalidImageException message

- src/main/groovy/edu/wpi/first/gradlerio/frc/FRCNativeArtifact.groovy
We used to do this in Eclipse, but it seems this was never ported to
GradleRIO.
> Give C++ programs permission to set RT thread priority

- src/main/groovy/edu/wpi/first/gradlerio/frc/InvalidImageException.groovy
Change firmware to image, since firmware and immage are different for the roboRIO
add links for updating wpilib and gradlerio
> Update image exception message

- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
> Fix RoboRIO DNS deploy addresses

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIPlugin.java
> Add wpilib maven repo vendor cache

- build.gradle
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIMavenExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIPlugin.java
- src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPINativeExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPIVendorMavenDependency.java
Update to native utils makes downloading dependencies orders of magnitude faster if they actually have to get downloaded
> Update to newest native utils

- build.gradle
Used to get latest deploy utils
> Update to latest native utils

- src/main/java/edu/wpi/first/gradlerio/wpi/java/WPIJavaExtension.java
> Fix application of -XstartOnFirstThread

- src/main/java/edu/wpi/first/gradlerio/deploy/DebugFileTask.java
- src/main/java/edu/wpi/first/gradlerio/deploy/DebugInfo.java
- src/main/java/edu/wpi/first/gradlerio/deploy/FRCDeployPlugin.java
- src/main/java/edu/wpi/first/gradlerio/deploy/FRCExtension.java
- src/main/java/edu/wpi/first/gradlerio/deploy/WPIRemoteTarget.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
Necessary for VS Code debugging
> Add debug info task

- src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPINativeExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPINativeVendorDepsExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.java
- src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/WPIVendorDepsExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/java/ExtractNativeJavaArtifacts.java
- src/main/java/edu/wpi/first/gradlerio/wpi/java/WPIJavaVendorDepsExtension.java
There were cases the C++ dependency set could be empty
> Fix vendor json loading ordering issues

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPIToolsPlugin.java
- versionupdates.gradle
This won't break the build, but will be needed for the installer to later grab it.
> Add roborio team number setter support

- src/main/java/edu/wpi/first/gradlerio/deploy/StagedDeployTarget.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCJREArtifact.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCJavaArtifact.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCNativeArtifact.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCProgramStartArtifact.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RobotCommandArtifact.java
The old method wasn't easily settable in the DSL. This is.
> Add way to configure deploy stage from DSL

- examples/cpp/build.gradle
- examples/java/build.gradle
- examples/jni/build.gradle
- examples/kotlin/build.gradle
- gradle.properties
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
- versionupdates.gradle
Also fix versionupdates.gradle for roboRIOTeamNumberSetter
> Update for 2022.1.1-beta-4

- build.gradle
- examples/cpp/build.gradle
- examples/cpp/gradle/wrapper/gradle-wrapper.properties
- examples/cpp/gradlew
- examples/java/build.gradle
- examples/java/gradle/wrapper/gradle-wrapper.properties
- examples/java/gradlew
- examples/jni/build.gradle
- examples/kotlin/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
> Update for 2022.1.1-rc-1

- README.md
That way we don't have to keep asking Thad how to do it. :)
> Document deploying experimental JDK 17

- src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPIToolsPlugin.java
Closes #390 
Would this need a change in the installer as well?
> Update Shuffleboard artifact location

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIExtension.java
The version needs to be passed down to work properly.
> Fix command vendor deps

- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
The new image already contains them
> Remove sed changes during deploy

- build.gradle
This reverts commit e81811aec21c58050626d9c4520a09ee4e6b2416.
> Revert "Update to native utils 2023.6.0 (#621)"

- .github/workflows/ci.yml
- testing/cpp/build.gradle
- testing/java/build.gradle
- testing/jni/build.gradle
- testing/kotlin/build.gradle
> Don't publish build folder from tests

- src/main/java/edu/wpi/first/gradlerio/wpi/simulation/SimulationExtension.java
This extension actually makes the sim compatible with the real DriverStation.
> Rename "Sim DriverStation" to be clearer about its purpose

- src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/tools/WPIToolsPlugin.java
> Don't configure SmartDashboard as a tool on mac arm

- README.md
https://www.chiefdelphi.com/t/teams-what-is-your-average-rio-cpu-utilization/433028/19 
https://www.chiefdelphi.com/t/teams-what-is-your-average-rio-cpu-utilization/433028/21
> Fix setting gcType docs and add docs for other GCs (NFC)

- src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPINativeCompileRules.java
Closes #655 
Its not easy in Java to open a file in an alternate format. So instead, just make an error here a warning and not an error.
> Handle MalformedInputException in warning printer

- src/main/java/edu/wpi/first/gradlerio/PreemptiveDownloadTask.java
- src/main/java/edu/wpi/first/gradlerio/wpi/dependencies/WPIDependenciesPlugin.java
- src/main/java/edu/wpi/first/gradlerio/wpi/java/TestTaskDoFirstAction.java
- src/main/java/edu/wpi/first/gradlerio/wpi/java/WPIJavaExtension.java
Theres some issues with the current one where it can be too eager at times.
> Fix extract tasks to actually be properly lazy

- src/main/java/edu/wpi/first/gradlerio/wpi/java/WPIJavaDepsExtension.java
Closes #662 
Won't build correctly until a beta release with wpiunits is published.
> Add wpiunits to java dependencies

- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCJavaArtifact.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/GarbageCollectorType.java
Serial GC seems to work much better for the working set FRC has
> Switch to serial GC by default

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/java/WPIJavaDepsExtension.java
To match wpilibsuite/allwpilib#5391.
> Add quickbuf Java dependency

- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/FRCProgramStartArtifact.java
> Warn and don't start program if NoApp is triggered

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
Required from [here](https://github.com/wpilibsuite/allwpilib/pull/6072)
> bump quickbuf version

- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/InvalidImageException.java
- src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java
The beta image would be detected as valid without this.
> Special case image check top ignore 2024_v2.0

- src/main/java/edu/wpi/first/gradlerio/OneDriveException.java
> Reword OneDrive error to be more useful

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- testing/asm/build.gradle
- testing/asm/gradle/wrapper/gradle-wrapper.properties
- testing/cpp/build.gradle
- testing/cpp/gradle/wrapper/gradle-wrapper.properties
- testing/java/build.gradle
- testing/java/gradle/wrapper/gradle-wrapper.properties
Fixes issues with reusing gradle daemon
> Update to gradle 8.10.2

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIExtension.java
The included configuration should prevent the eclipse compiler from generating partial/corrupt epilogue classes, allowing simulation, debugging, and intellisense to work
Closes https://github.com/wpilibsuite/vscode-wpilib/issues/716 (OBE)
Resolves https://github.com/wpilibsuite/allwpilib/issues/7103
Resolves https://github.com/wpilibsuite/2025Beta/issues/20
Thanks to https://github.com/redhat-developer/vscode-java/issues/1660#issuecomment-818274055
Replaces https://github.com/wpilibsuite/vscode-wpilib/pull/717
> Add eclipse workaround for annotation processors

- README.md
- build.gradle
- gradle.properties
- settings.gradle
- src/test/groovy/edu/wpi/first/gradlerio/GradleRioInitializationTest.groovy
- testing/_archived/coprocessor_cpp/build.gradle
- testing/_archived/coprocessor_java/build.gradle
- testing/asm/build.gradle
- testing/cpp/build.gradle
- testing/java/build.gradle
- testing/jni/build.gradle
- testing/kotlin/build.gradle
This way we don't need to worry about version conflicts.
> Switch plugin to publish as GradleRIO2027

- build.gradle
- gradle.properties
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIVersionsExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/cpp/WPINativeDepsExtension.java
- src/main/java/edu/wpi/first/gradlerio/wpi/java/WPIJavaDepsExtension.java
- testing/asm/build.gradle
- testing/cpp/build.gradle
- testing/java/build.gradle
- testing/jni/build.gradle
> Add datalog

- gradle.properties
- src/main/java/edu/wpi/first/gradlerio/wpi/WPIExtension.java
- testing/asm/build.gradle
- testing/asm/settings.gradle
- testing/cpp/build.gradle
- testing/cpp/settings.gradle
- testing/java/build.gradle
- testing/java/settings.gradle
- testing/jni/build.gradle
- testing/jni/settings.gradle
This will let us update between alphas and betas in the futures.
> Update maven folder to 2027_alpha1

- src/main/java/edu/wpi/first/gradlerio/wpi/WPIExtension.java
> Remove JRE artifacts

- build.gradle
depends on wpilibsuite/native-utils#253
> Update download plugin for parallel downloads
